import type { EventState } from "@/domain/guardian-heart/types/game";

export const MINIMAL_EVENTS: Omit<EventState, "contributions" | "revealedAtRound">[] = [
  {
    cardId: "event_1_rockfall",
    nameZh: "地鳴與落石",
    rulesTextZh: "立即效果：全隊失去 1SR。解決條件：事件處理區投入 3SR。",
    unresolvedPenaltyTextZh: "未解懲罰：全隊再失去 1SR。",
    requirement: { srRequired: 3, spRequired: 0 },
    immediateEffect: { mode: "each_player", srLoss: 1 },
    penalty: { srLoss: 1, mode: "each_player" },
    tags: ["sr", "all_players", "sealed", "first_round_pool"],
  },
  {
    cardId: "event_2_lost_child",
    nameZh: "走散的無助孩童",
    rulesTextZh: "立即效果：全隊失去 1SP。解決條件：事件處理區投入 3SP。",
    unresolvedPenaltyTextZh: "未解懲罰：指定 2 名不同玩家，各失去 1SP。",
    requirement: { srRequired: 0, spRequired: 3 },
    immediateEffect: { mode: "each_player", spLoss: 1 },
    penalty: { spLoss: 1, mode: "two_distinct_players", targetCount: 2 },
    tags: ["sp", "two_targets", "sealed", "first_round_pool"],
  },
  {
    cardId: "event_3_food_anxiety",
    nameZh: "糧食短缺的焦慮",
    rulesTextZh: "立即效果：全隊失去 1SP。解決條件：事件處理區投入 2SR＋2SP。",
    unresolvedPenaltyTextZh: "未解懲罰：全隊再失去 1SP。",
    requirement: { srRequired: 2, spRequired: 2 },
    immediateEffect: { mode: "each_player", spLoss: 1 },
    penalty: { spLoss: 1, mode: "each_player" },
    tags: ["mixed", "all_players", "sealed", "first_round_pool"],
  },
  {
    cardId: "event_4_rescue_fatigue",
    nameZh: "日夜救援的疲勞",
    rulesTextZh: "立即效果：全隊失去 1SP。解決條件：事件處理區投入 1SR＋2SP。",
    unresolvedPenaltyTextZh: "未解懲罰：每名玩家各自選擇失去 1SR 或 1SP。",
    requirement: { srRequired: 1, spRequired: 2 },
    immediateEffect: { mode: "each_player", spLoss: 1 },
    penalty: { srLoss: 1, spLoss: 1, mode: "each_player_choose_sr_or_sp" },
    tags: ["tempo", "choice", "sealed", "first_round_pool"],
  },
  {
    cardId: "event_5_isolation_night",
    nameZh: "黑夜迷途的孤立感",
    rulesTextZh: "立即效果：翻開此事件時，所有未與任何隊友相鄰的玩家，各失去 1SP。解決條件：事件處理區投入 3SP。",
    unresolvedPenaltyTextZh: "未解懲罰：全隊失去 1SP。",
    requirement: { srRequired: 0, spRequired: 3 },
    immediateEffect: { mode: "each_player_not_adjacent_to_any_teammate", spLoss: 1 },
    penalty: { spLoss: 1, mode: "each_player" },
    tags: ["mutual_aid", "isolation", "sealed", "first_round_pool"],
  },
  {
    cardId: "event_6_blame",
    nameZh: "恐慌下的相互指責",
    rulesTextZh: "立即效果：全隊失去 1SP。解決條件：事件處理區投入 4SP。",
    unresolvedPenaltyTextZh: "未解懲罰：全隊再失去 1SP。",
    requirement: { srRequired: 0, spRequired: 4 },
    immediateEffect: { mode: "each_player", spLoss: 1 },
    penalty: { spLoss: 1, mode: "each_player" },
    tags: ["sp", "observe_4sp", "sealed", "first_round_pool"],
  },
  {
    cardId: "event_7_long_night",
    nameZh: "長夜降臨與集體恐慌",
    rulesTextZh: "立即效果：全隊失去 1SP。解決條件：事件處理區投入 3SR＋2SP。",
    unresolvedPenaltyTextZh: "未解懲罰：全隊失去 1SR。",
    requirement: { srRequired: 3, spRequired: 2 },
    immediateEffect: { mode: "each_player", spLoss: 1 },
    penalty: { srLoss: 1, mode: "each_player" },
    tags: ["high_pressure", "mixed", "sealed", "first_round_pool"],
  },
  {
    cardId: "event_8_chain_disaster",
    nameZh: "聯絡斷的連鎖天災",
    rulesTextZh: "立即效果：全隊失去 1SR。解決條件：事件處理區投入 3SR＋1SP。",
    unresolvedPenaltyTextZh: "未解懲罰：指定 2 名不同玩家，各失去 1SR。",
    requirement: { srRequired: 3, spRequired: 1 },
    immediateEffect: { mode: "each_player", srLoss: 1 },
    penalty: { srLoss: 1, mode: "two_distinct_players", targetCount: 2 },
    tags: ["high_pressure", "two_targets", "sealed", "first_round_pool"],
  },
];
