import type { TaskState } from "@/domain/guardian-heart/types/game";

export const MINIMAL_TASKS: TaskState[] = [
  {
    taskId: "task_temporary_supply_line",
    nameZh: "臨時補給線",
    rulesTextZh: "營火階段宣告時，至少 1 名玩家位於物資站，且全隊至少有 2 名玩家的 SR 不低於 3。",
    completionHintZh: "觀察是否有人位於物資站，且至少兩名玩家 SR ≧ 3。",
    rewardTextZh: "完成獎勵：指定 2 名玩家，各回復 1SR。",
    rewardSpec: { type: "recover_two_players", resource: "SR", amount: 1 },
    declaredAtRound: null,
    declaredBySeat: null,
    completionCheckedByHost: false,
    rewardGrantedAtRound: null,
  },
  {
    taskId: "task_comfort_circle",
    nameZh: "安心陪伴圈",
    rulesTextZh: "營火階段宣告時，至少 1 名玩家位於庇護所，且全隊至少有 2 名玩家的 SP 不低於 3。",
    completionHintZh: "觀察是否有人位於庇護所，且至少兩名玩家 SP ≧ 3。",
    rewardTextZh: "完成獎勵：指定 2 名玩家，各回復 1SP。",
    rewardSpec: { type: "recover_two_players", resource: "SP", amount: 1 },
    declaredAtRound: null,
    declaredBySeat: null,
    completionCheckedByHost: false,
    rewardGrantedAtRound: null,
  },
  {
    taskId: "task_neighborhood_relay",
    nameZh: "街坊接力",
    rulesTextZh: "本輪發生過 2 次 0AP 相鄰互助。",
    completionHintZh: "至少要有兩次 0AP 相鄰互助。",
    rewardTextZh: "完成獎勵：指定 2 名玩家，各回復 1 點資源（SR 或 SP 自選）。",
    rewardSpec: { type: "recover_two_players_choice", amount: 1 },
    declaredAtRound: null,
    declaredBySeat: null,
    completionCheckedByHost: false,
    rewardGrantedAtRound: null,
  },
  {
    taskId: "task_crisis_control",
    nameZh: "危機控管",
    rulesTextZh: "營火階段宣告時，本輪事件已被成功解決，且無人位於風險地格。",
    completionHintZh: "本輪事件需成功解決，且全員離開風險地格。",
    rewardTextZh: "完成獎勵：壓力值 -1。",
    rewardSpec: { type: "reduce_pressure", amount: 1 },
    declaredAtRound: null,
    declaredBySeat: null,
    completionCheckedByHost: false,
    rewardGrantedAtRound: null,
  },
  {
    taskId: "task_small_gathering_point",
    nameZh: "安置小聚點",
    rulesTextZh: "營火階段宣告時，至少 3 名玩家位於同一地格。",
    completionHintZh: "檢查是否有 3 名以上玩家同格。",
    rewardTextZh: "完成獎勵：指定 2 名玩家，各回復 1SP；再抽 1 張行動卡。",
    rewardSpec: { type: "recover_two_players_and_draw_declared_seat", resource: "SP", recoverAmount: 1, drawAmount: 1 },
    declaredAtRound: null,
    declaredBySeat: null,
    completionCheckedByHost: false,
    rewardGrantedAtRound: null,
  },
  {
    taskId: "task_support_network_formed",
    nameZh: "支援網成形",
    rulesTextZh: "本輪至少發生 2 次 0AP 相鄰互助，且 SR 互助與 SP 互助各至少 1 次。",
    completionHintZh: "至少兩次互助，且 SR / SP 互助都要出現。",
    rewardTextZh: "完成獎勵：全隊各回復 1SP。",
    rewardSpec: { type: "recover_all_players", resource: "SP", amount: 1 },
    declaredAtRound: null,
    declaredBySeat: null,
    completionCheckedByHost: false,
    rewardGrantedAtRound: null,
  },
];
